//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellPhoneService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeDieuHanh
    {
        public HeDieuHanh()
        {
            this.ChiTietSanPhams = new HashSet<ChiTietSanPham>();
        }
    
        public string MaHDH { get; set; }
        public string Ten { get; set; }
        public string PhienBan { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<ChiTietSanPham> ChiTietSanPhams { get; set; }
    }
}
