//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellPhoneService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.GioHangs = new HashSet<GioHang>();
            this.DanhGias = new HashSet<DanhGia>();
            this.SoSanhGias = new HashSet<SoSanhGia>();
        }
    
        public int MaSP { get; set; }
        public int MaLSP { get; set; }
        public int MaNSX { get; set; }
        public string TenSP { get; set; }
        public double GiaBanHienHanh { get; set; }
        public int SoLuong { get; set; }
        public string HinhAnhDaiDien { get; set; }
        public int MaCTSP { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public double DiemDanhGia { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ChiTietSanPham ChiTietSanPham { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual ICollection<SoSanhGia> SoSanhGias { get; set; }
    }
}
