//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellPhoneService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoSanhGia
    {
        public int MaSo { get; set; }
        public int MaSP { get; set; }
        public string MaWebsite { get; set; }
        public string Gia { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual Website Website { get; set; }
    }
}
