//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellPhoneService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamSo
    {
        public int MaSo { get; set; }
        public string NoiDung { get; set; }
        public string GiaTri { get; set; }
        public string KieuDuLieu { get; set; }
    }
}
