//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellPhoneService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaSo { get; set; }
        public string TieuDe { get; set; }
        public string Link { get; set; }
        public string Hinh { get; set; }
        public string MoTa { get; set; }
        public System.DateTime Ngay { get; set; }
    }
}
