//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellPhoneService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public Website()
        {
            this.SoSanhGias = new HashSet<SoSanhGia>();
        }
    
        public string MaSo { get; set; }
        public string Ten { get; set; }
        public string Link { get; set; }
        public string LinkTimKiem { get; set; }
    
        public virtual ICollection<SoSanhGia> SoSanhGias { get; set; }
    }
}
